### ISSUE TITLE
[Request] tooltip between flags

### ISSUE THREAD

**Issue by edyarchi** [Humberd/Stuff-unlocked#3]
This is not a isuee but just a request. I don't know how to do a request, so sorry if this not the right place.

Before the event "Hot Summer" there was a useful tooltip, in the War page, just between the two flags of each battle, when the mouse pointer was "hovering" the tank/airplane icon.

That tooltip tooltip showed a preview of the battle's top damage, with no need to enter in the battle.

It was removed by Zordacz because it was not compatible with the event "Hot Summer".

Is it possible to have that tooltip back?

**Comment by Humberd** [comment]
I'll try to dig through the source code to check if it was only disabled or removed completely. Do you maybe have a script from before that event? Or even a screenshot of that tooltip? I'm asking for a screenshot because I need some unique string to query by in the code, to find it, because there is no such thing named as a tooltip now

**Comment by edyarchi** [comment]
Sorry, I don't keep the previous scripts. Nor have I ever taken screenshots of that feature.
It is logical to assume that it was simply disabled in order to enable it again at the end of the event.

**Comment by Humberd** [comment]
You are technically right. I'll give it another search

**Comment by Humberd** [comment]
Were there player names for a given battle in that tooltip?

If so, then the script must send a request to `/military/battle-console` endpoint, because only via it we can access that data. However, we can do it only in 2 cases - both on given battle, not the campaigns list:

1. When we listen to "Epic progress" via a checkbox in the bottom left corner
https://github.com/Humberd/Stuff-unlocked/blob/5db5382f8e3f12cf2fbfc6cc605e517101350c62/src/index.user.js#L1478-L1490 
2. When we show stats in the top left and right corners with top 10 people.
https://github.com/Humberd/Stuff-unlocked/blob/5db5382f8e3f12cf2fbfc6cc605e517101350c62/src/index.user.js#L1495-L1510

**Comment by edyarchi** [comment]
Yes, 
in the tooltip there were the names of the top n players (I guess n=5) for each side, with their damage.
If I remember well, the data appear only for your division.

**Comment by Humberd** [comment]
I'm afraid it's gone or pretty well hidden :/ If you somehow get a screenshot of it I could recreate it, or if you acquire a script with version less than 5.38 then I could revert it.

**Comment by ghost** [comment]
If I may, use this: https://curlybear.eu/scripts - Warspage+. Back then, Zordacz didn't just disable it, afterwards the code changed and he gave up on this option. Hence the new dedicated script, developed by someone else.
